### ISSUE TITLE
Fine-grained progress bars don't work in debug mode

### ISSUE THREAD

**Issue by tocklime** [mitsuhiko/indicatif#206]
I think the changes you made in https://github.com/mitsuhiko/indicatif/commit/3cbd533da3eda9162da8955ead6218a022b0604b broke fine grained progress bars. In style.rs, line 164 now says
```rust
                n.saturating_sub((fill * n) % n)
```
where fill and n are both usize. This must always evaluate to n.saturating_sub(0), and hence the middle characters are never used.

One way to fix this is to change that line to 
```rust
                n.saturating_sub((pct * width as f32 * n as f32) as usize % n)
```

Which works for me, but it would probably be better to keep the `fill : f32` around as well as the `fill : usize`, and not have to recalculate things.

**Comment by tocklime** [comment]
Hmm. I've tried this in release mode, and it seems to work there.

**Comment by marienz** [comment]
I don't understand why this works for you in release mode. The "finebars" example does not work for me in release mode, and the bug in the commit you flagged (`fill` is now a `usize` instead of a float, so `(fill * n) % n` is always 0 and we always select the same character) looks like it should occur no matter the build mode.

#233 should fix it.
