### ISSUE TITLE
Using rayon's `par_iter`, progress' are not rendered properly.   

### ISSUE THREAD

**Issue by pjmp** [mitsuhiko/indicatif#269]
![rayon-ind](https://user-images.githubusercontent.com/11157420/113993948-ac57de00-9874-11eb-8a19-2470e89b005a.gif)

Steps to reproduce:

1) Clone: https://github.com/pjmp/indicatif-rayon 
2) `cargo run`

Toggle comments in [line 11-14](https://github.com/pjmp/indicatif-rayon/blob/0f135e1455cc520722e7aec3df6ce42e3683f489/src/main.rs#L11-L14) to see the difference.

**Comment by djc** [comment]
Can you try with indicatif's main branch? There've been quite a few changes.

**Comment by mibac138** [comment]
This is somewhat expected. When you call `set_draw_target` you unlink the progress bar from the multi progress. When you have a single thread, each progress bar is drawn sequentially, one after another, seemingly working fine, however when you run the progress bars concurrently the bug is now exposed as they draw concurrently and override one another. You probably want to remove `ProgressBar::set_draw_target` and instead use `MultiProgress::set_draw_target`.
