### ISSUE TITLE
Hex colors

### ISSUE THREAD

**Issue by jafioti** [mitsuhiko/indicatif#302]
Is it possible to use Hex or RGB colors instead of only the preset ones? I haven't seen an example of this feature, so I didn't know if it was supported or not. If not, is it planned?

**Comment by djc** [comment]
indicatif just uses the console crate for CLI colorization. This question is probably better asked upstream.

https://docs.rs/console/0.14.1/console/enum.Color.html

**Comment by LeCyberDucky** [comment]
Hey, I'm not sure what the customs on GitHub are when it comes to responding to closed issues. But I was having the same issue, so I hope it's okay that I respond with a solution here, in case other people are trying to figure this out as well.

As it turns out, the changes necessary for this were recently added to `console`. See these links: 
https://github.com/mitsuhiko/console/pull/72 
https://github.com/mitsuhiko/console/pull/98

The most recent release of `console` doesn't reflect this yet, however, and therefore this doesn't directly work in `indicatif` yet. But you can force the use of these fixes by adding the following to your Cargo.toml: 

```
[patch.crates-io]
console = { git = "https://github.com/mitsuhiko/console"}
```

With that, `indicatif` will use `console` directly from GitHub, including the necessary changes. Therefore, you can then do something like the following to use color 130 on 56, which gives you an orange progress bar on a purple background: 

```
let progress_bar = ProgressBar::new(length).with_style(
        ProgressStyle::default_bar().template("{wide_bar:.130.on_56}")
    );
```
